package com.example.trivialapp_base.model

// Definición de la clase de datos Pregunta según requisitos
data class Pregunta(
    val pregunta: String,
    val categoria: String,
    val dificultad: String, // "Facil", "Medio", "Dificil"
    val respuesta1: String,
    val respuesta2: String,
    val respuesta3: String,
    val respuesta4: String,
    val respuestaCorrecta: String // Debe coincidir con una de las anteriores
)

// Objeto para simular la base de datos local (Hardcoded)
object ProveedorPreguntas {
    fun obtenerPreguntas(): MutableList<Pregunta> {
        return mutableListOf(

            // ==================== FÁCIL (30) ====================
            Pregunta("¿Capital de Francia?", "Geografía", "Facil", "Madrid", "París", "Roma", "Berlín", "París"),
            Pregunta("¿Fórmula del agua?", "Ciencia", "Facil", "H2O", "CO2", "O2", "H2O2", "H2O"),
            Pregunta("¿Autor del Quijote?", "Literatura", "Facil", "Cervantes", "Quevedo", "Lope", "Góngora", "Cervantes"),
            Pregunta("¿Planeta rojo?", "Ciencia", "Facil", "Marte", "Júpiter", "Venus", "Saturno", "Marte"),
            Pregunta("¿Capital de España?", "Geografía", "Facil", "Barcelona", "Madrid", "Sevilla", "Valencia", "Madrid"),
            Pregunta("¿Rey de los dioses griegos?", "Mitología", "Facil", "Zeus", "Hades", "Ares", "Apolo", "Zeus"),
            Pregunta("¿Animal que ladra?", "Naturaleza", "Facil", "Gato", "Perro", "Vaca", "Caballo", "Perro"),
            Pregunta("¿Color del cielo?", "General", "Facil", "Verde", "Rojo", "Azul", "Amarillo", "Azul"),
            Pregunta("¿Cuántos días tiene una semana?", "General", "Facil", "5", "6", "7", "8", "7"),
            Pregunta("¿Lenguaje de Android?", "Tecnología", "Facil", "Swift", "Kotlin", "PHP", "Ruby", "Kotlin"),
            Pregunta("¿Capital de Italia?", "Geografía", "Facil", "Milán", "Roma", "Venecia", "Nápoles", "Roma"),
            Pregunta("¿Mamífero más grande?", "Naturaleza", "Facil", "Elefante", "Ballena azul", "Rinoceronte", "Hipopótamo", "Ballena azul"),
            Pregunta("¿Resultado de 2+2?", "Matemáticas", "Facil", "3", "4", "5", "6", "4"),
            Pregunta("¿Mes con Navidad?", "General", "Facil", "Enero", "Febrero", "Diciembre", "Marzo", "Diciembre"),
            Pregunta("¿Capital de Portugal?", "Geografía", "Facil", "Oporto", "Lisboa", "Faro", "Braga", "Lisboa"),
            Pregunta("¿Deporte de Messi?", "Deportes", "Facil", "Tenis", "Fútbol", "Baloncesto", "Golf", "Fútbol"),
            Pregunta("¿Animal que maúlla?", "Naturaleza", "Facil", "Perro", "Gato", "León", "Tigre", "Gato"),
            Pregunta("¿Día después del lunes?", "General", "Facil", "Domingo", "Martes", "Viernes", "Sábado", "Martes"),
            Pregunta("¿Capital de Alemania?", "Geografía", "Facil", "Múnich", "Berlín", "Hamburgo", "Frankfurt", "Berlín"),
            Pregunta("¿Océano más grande?", "Geografía", "Facil", "Atlántico", "Índico", "Pacífico", "Ártico", "Pacífico"),
            Pregunta("¿Moneda de EE.UU.?", "Economía", "Facil", "Euro", "Dólar", "Yen", "Libra", "Dólar"),
            Pregunta("¿Forma de la Tierra?", "Ciencia", "Facil", "Plana", "Cuadrada", "Redonda", "Triangular", "Redonda"),
            Pregunta("¿Color de la sangre?", "Biología", "Facil", "Azul", "Rojo", "Verde", "Negro", "Rojo"),
            Pregunta("¿Héroe de Gotham?", "Cine", "Facil", "Superman", "Batman", "Spiderman", "Iron Man", "Batman"),
            Pregunta("¿Animal más rápido?", "Naturaleza", "Facil", "León", "Guepardo", "Tigre", "Caballo", "Guepardo"),
            Pregunta("¿Idioma de Brasil?", "Geografía", "Facil", "Español", "Portugués", "Inglés", "Francés", "Portugués"),
            Pregunta("¿Capital de Argentina?", "Geografía", "Facil", "Rosario", "Córdoba", "Buenos Aires", "La Plata", "Buenos Aires"),
            Pregunta("¿Estación más fría?", "General", "Facil", "Verano", "Otoño", "Invierno", "Primavera", "Invierno"),
            Pregunta("¿Instrumento con teclas?", "Música", "Facil", "Guitarra", "Piano", "Violín", "Flauta", "Piano"),
            Pregunta("¿Número romano V?", "Historia", "Facil", "1", "5", "10", "50", "5"),

            // ==================== MEDIO (30) ====================
            Pregunta("¿Planeta más grande?", "Ciencia", "Medio", "Tierra", "Marte", "Júpiter", "Saturno", "Júpiter"),
            Pregunta("¿Año descubrimiento América?", "Historia", "Medio", "1492", "1500", "1485", "1600", "1492"),
            Pregunta("¿Hueso más largo?", "Anatomía", "Medio", "Tibia", "Húmero", "Fémur", "Radio", "Fémur"),
            Pregunta("¿Moneda de Japón?", "Economía", "Medio", "Yuan", "Won", "Yen", "Dólar", "Yen"),
            Pregunta("¿Autor de Hamlet?", "Literatura", "Medio", "Shakespeare", "Cervantes", "Dante", "Molière", "Shakespeare"),
            Pregunta("¿Capital de Canadá?", "Geografía", "Medio", "Toronto", "Vancouver", "Ottawa", "Montreal", "Ottawa"),
            Pregunta("¿Elemento Au?", "Química", "Medio", "Plata", "Oro", "Cobre", "Hierro", "Oro"),
            Pregunta("¿Río más largo?", "Geografía", "Medio", "Nilo", "Amazonas", "Yangtsé", "Danubio", "Amazonas"),
            Pregunta("¿País del Taj Mahal?", "Historia", "Medio", "China", "India", "Pakistán", "Nepal", "India"),
            Pregunta("¿Sistema solar tiene cuántos planetas?", "Ciencia", "Medio", "7", "8", "9", "10", "8"),
            Pregunta("¿Lenguaje web?", "Tecnología", "Medio", "HTML", "Kotlin", "Swift", "C++", "HTML"),
            Pregunta("¿Capital de Australia?", "Geografía", "Medio", "Sydney", "Melbourne", "Canberra", "Perth", "Canberra"),
            Pregunta("¿Órgano que bombea sangre?", "Biología", "Medio", "Pulmón", "Cerebro", "Corazón", "Riñón", "Corazón"),
            Pregunta("¿Autor de La Odisea?", "Literatura", "Medio", "Homero", "Platón", "Sófocles", "Aristóteles", "Homero"),
            Pregunta("¿Metal líquido?", "Química", "Medio", "Plomo", "Mercurio", "Aluminio", "Zinc", "Mercurio"),
            Pregunta("¿Capital de Noruega?", "Geografía", "Medio", "Estocolmo", "Oslo", "Helsinki", "Copenhague", "Oslo"),
            Pregunta("¿Continente más grande?", "Geografía", "Medio", "África", "Europa", "Asia", "América", "Asia"),
            Pregunta("¿Inventor bombilla?", "Historia", "Medio", "Tesla", "Edison", "Newton", "Bell", "Edison"),
            Pregunta("¿Capital de Grecia?", "Geografía", "Medio", "Atenas", "Roma", "Sofía", "Estambul", "Atenas"),
            Pregunta("¿Animal ovíparo?", "Biología", "Medio", "Perro", "Vaca", "Gallina", "Delfín", "Gallina"),
            Pregunta("¿País de las pirámides?", "Historia", "Medio", "México", "Egipto", "Perú", "Sudán", "Egipto"),
            Pregunta("¿Autor de 1984?", "Literatura", "Medio", "Orwell", "Huxley", "Bradbury", "Asimov", "Orwell"),
            Pregunta("¿Capital de Suiza?", "Geografía", "Medio", "Zúrich", "Ginebra", "Berna", "Basilea", "Berna"),
            Pregunta("¿Unidad de fuerza?", "Física", "Medio", "Watt", "Newton", "Joule", "Pascal", "Newton"),
            Pregunta("¿Mar más grande?", "Geografía", "Medio", "Rojo", "Negro", "Mediterráneo", "Caspio", "Caspio"),
            Pregunta("¿Órgano de la vista?", "Biología", "Medio", "Nariz", "Ojo", "Oído", "Lengua", "Ojo"),
            Pregunta("¿Capital de Irlanda?", "Geografía", "Medio", "Cork", "Galway", "Dublín", "Belfast", "Dublín"),
            Pregunta("¿Principal gas atmósfera?", "Ciencia", "Medio", "Oxígeno", "Nitrógeno", "CO2", "Hidrógeno", "Nitrógeno"),
            Pregunta("¿Autor de El Principito?", "Literatura", "Medio", "Saint-Exupéry", "Verne", "Hugo", "Camus", "Saint-Exupéry"),
            Pregunta("¿País más poblado?", "Geografía", "Medio", "India", "EE.UU.", "China", "Rusia", "India"),

            // ==================== DIFÍCIL (30) ====================
            Pregunta("¿Velocidad de la luz?", "Física", "Dificil", "150.000 km/s", "300.000 km/s", "1.000 km/s", "30.000 km/s", "300.000 km/s"),
            Pregunta("¿Número de huesos humanos?", "Anatomía", "Dificil", "200", "206", "210", "180", "206"),
            Pregunta("¿Capital de Mongolia?", "Geografía", "Dificil", "Astana", "Ulán Bator", "Taskent", "Biskek", "Ulán Bator"),
            Pregunta("¿Año caída Constantinopla?", "Historia", "Dificil", "1453", "1492", "1400", "1517", "1453"),
            Pregunta("¿Constante de Planck?", "Física", "Dificil", "6.62×10⁻³⁴", "9.8", "3×10⁸", "1.6×10⁻¹⁹", "6.62×10⁻³⁴"),
            Pregunta("¿Lenguaje bajo nivel?", "Tecnología", "Dificil", "Python", "Java", "Assembly", "PHP", "Assembly"),
            Pregunta("¿Autor de La Divina Comedia?", "Literatura", "Dificil", "Petrarca", "Boccaccio", "Dante", "Virgilio", "Dante"),
            Pregunta("¿País de Transilvania?", "Geografía", "Dificil", "Hungría", "Rumanía", "Bulgaria", "Serbia", "Rumanía"),
            Pregunta("¿Metal más conductor?", "Física", "Dificil", "Cobre", "Plata", "Oro", "Aluminio", "Plata"),
            Pregunta("¿Teoría de Einstein?", "Física", "Dificil", "Evolución", "Relatividad", "Cuántica", "Gravedad", "Relatividad"),
            Pregunta("¿Capital de Sri Lanka?", "Geografía", "Dificil", "Colombo", "Kandy", "Sri Jayawardenepura Kotte", "Galle", "Sri Jayawardenepura Kotte"),
            Pregunta("¿Número atómico del carbono?", "Química", "Dificil", "4", "6", "8", "12", "6"),
            Pregunta("¿Autor del Leviatán?", "Filosofía", "Dificil", "Locke", "Hobbes", "Rousseau", "Hume", "Hobbes"),
            Pregunta("¿Capital de Burkina Faso?", "Geografía", "Dificil", "Bamako", "Niamey", "Uagadugú", "Lomé", "Uagadugú"),
            Pregunta("¿Hueso del oído?", "Anatomía", "Dificil", "Estribo", "Fémur", "Radio", "Cúbito", "Estribo"),
            Pregunta("¿Autor de Crimen y Castigo?", "Literatura", "Dificil", "Tolstói", "Dostoyevski", "Pushkin", "Gogol", "Dostoyevski"),
            Pregunta("¿Mar interior de Asia?", "Geografía", "Dificil", "Aral", "Rojo", "Negro", "Báltico", "Aral"),
            Pregunta("¿Gas noble?", "Química", "Dificil", "Nitrógeno", "Helio", "Oxígeno", "Hidrógeno", "Helio"),
            Pregunta("¿Año Revolución Francesa?", "Historia", "Dificil", "1789", "1776", "1804", "1750", "1789"),
            Pregunta("¿Capital de Eritrea?", "Geografía", "Dificil", "Asmara", "Jartum", "Adís Abeba", "Yibuti", "Asmara"),
            Pregunta("¿Fuerza que atrae masas?", "Física", "Dificil", "Magnética", "Gravitatoria", "Eléctrica", "Nuclear", "Gravitatoria"),
            Pregunta("¿Obra de Maquiavelo?", "Filosofía", "Dificil", "El Príncipe", "Utopía", "República", "Contrato Social", "El Príncipe"),
            Pregunta("¿Capital de Papúa Nueva Guinea?", "Geografía", "Dificil", "Suva", "Port Moresby", "Honiara", "Nukuʻalofa", "Port Moresby"),
            Pregunta("¿Unidad de resistencia?", "Física", "Dificil", "Voltio", "Ohmio", "Amperio", "Watt", "Ohmio"),
            Pregunta("¿Autor de Rayuela?", "Literatura", "Dificil", "Borges", "Cortázar", "Sábato", "Fuentes", "Cortázar"),
            Pregunta("¿Capital de Kazajistán?", "Geografía", "Dificil", "Almaty", "Astana", "Tashkent", "Bishkek", "Astana"),
            Pregunta("¿Tipo de enlace NaCl?", "Química", "Dificil", "Covalente", "Iónico", "Metálico", "Puente H", "Iónico"),
            Pregunta("¿Órgano del sistema linfático?", "Biología", "Dificil", "Bazo", "Hígado", "Páncreas", "Riñón", "Bazo"),
            Pregunta("¿Capital de Belice?", "Geografía", "Dificil", "Belmopán", "Belice City", "San José", "Tegucigalpa", "Belmopán")
        )
    }
}